using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KsFetch
{

    public enum SubCategoryKind
    {

        Art_Ceramics = 1,
        Art_ConceptualArt,
        Art_DigitalArt,
        Art_Illustration,
        Art_Installations,
        Art_MixedMedia,
        Art_Painting,
        Art_PerformanceArt,
        Art_PublicArt,
        Art_Sculpture,
        Art_Textiles,
        Art_VideoArt,

        Comics_Anthologies,
        Comics_ComicBooks,
        Comics_Events,
        Comics_GraphicNovels,
        Comics_Webcomics,

        Crafts_Candles,
        Crafts_Crochet,
        Crafts_DIY,
        Crafts_Embroidery,
        Crafts_Glass,
        Crafts_Knitting,
        Crafts_Letterpress,
        Crafts_Pottery,
        Crafts_Printing,
        Crafts_Quilts,
        Crafts_Stationery,
        Crafts_Taxidermy,
        Crafts_Weaving,
        Crafts_Woodworking,

        Dance_Performances,
        Dance_Residencies,
        Dance_Spaces,
        Dance_Workshops,

        Design_Architecture,
        Design_CivilDesign,
        Design_GraphicDesign,
        Design_InteractiveDesign,
        Design_ProductDesign,
        Design_Typography,

        Fashion_Accessories,
        Fashion_Apparel,
        Fashion_Childrenswear,
        Fashion_Couture,
        Fashion_Footwear,
        Fashion_Jewelery,
        Fashion_PetFashion,
        Fashion_ReadyToWear,

        FilmAndVideo_Action,
        FilmAndVideo_Animation,
        FilmAndVideo_Comedy,
        FilmAndVideo_Documentary,
        FilmAndVideo_Drama,
        FilmAndVideo_Experimental,
        FilmAndVideo_Family,
        FilmAndVideo_Fantasy,
        FilmAndVideo_Festivals,
        FilmAndVideo_Horror,
        FilmAndVideo_MovieTheaters,
        FilmAndVideo_MusicVideos,
        FilmAndVideo_NarrativeFilm,
        FilmAndVideo_Romance,
        FilmAndVideo_ScienceFiction,
        FilmAndVideo_Shorts,
        FilmAndVideo_Television,
        FilmAndVideo_Thrillers,
        FilmAndVideo_Webseries,

        Food_Bacon,
        Food_CommunityGardens,
        Food_Cookbooks,
        Food_Drinks,
        Food_Events,
        Food_FarmersMarkets,
        Food_Farms,
        Food_FoodTrucks,
        Food_Restaurants,
        Food_SmallBatch,
        Food_Spaces,
        Food_Vegan,

        Games_GamingHardware,
        Games_LiveGames,
        Games_MobileGames,
        Games_PlayingCards,
        Games_Puzzles,
        Games_TabletopGames,
        Games_VideoGames,

        Journalism_Audio,
        Journalism_Photo,
        Journalism_Print,
        Journalism_Video,
        Journalism_Web,

        Music_Blues,
        Music_Chiptune,
        Music_ClassicalMusic,
        Music_CountryAndFolk,
        Music_ElectronicalMusic,
        Music_Faith,
        Music_HipHop,
        Music_IndieRock,
        Music_Jazz,
        Music_Kids,
        Music_Latin,
        Music_Metal,
        Music_Pop,
        Music_Punk,
        Music_RNB,
        Music_Rock,
        Music_WorldMusic,

        Photography_Animals,
        Photography_FineArt,
        Photography_Nature,
        Photography_People,
        Photography_Photobooks,
        Photography_Places,

        Publishing_Academic,
        Publishing_Anthologies,
        Publishing_ArtBooks,
        Publishing_Calendars,
        Publishing_ChildrensBooks,
        Publishing_Fiction,
        Publishing_LiteraryJournals,
        Publishing_Nonfiction,
        Publishing_Periodicals,
        Publishing_Poetry,
        Publishing_RadioAndPodcasts,
        Publishing_Translations,
        Publishing_YoungAdult,
        Publishing_Zines,

        Technologies_3DPrinting,
        Technologies_Apps,
        Technologies_CameraEquipemnt,
        Technologies_DiyElectronics,
        Technologies_FabricationTools,
        Technologies_Flight,
        Technologies_Gadgets,
        Technologies_Hardware,
        Technologies_Marketspaces,
        Technologies_Robots,
        Technologies_Software,
        Technologies_Sound,
        Technologies_SpaceExploration,
        Technologies_Wearables,
        Technologies_Web,

        Theater_Experimental,
        Theater_Festivals,
        Theater_Immersive,
        Theater_Musical,
        Theater_Plays,
        Theater_Spaces

    }

}
